server:
  port: 9007
feign:
  okhttp:
    enabled: true

bi:
  git:
    bark:
      repo-name: bi-config
      bark-host: https://github.com/supermc90/bi-config.git
      bark-config-file-name: bi-config.json
      repo-path: /etc/jgit/repo
  bark:
    duration: 5 # 每次轮询间隔时间（s）
spring:
  profiles:
    active: home
